nave/lod/urls.py
# -*- coding: utf-8 -*-
"""
This module contains all the routing rules for the Linked Open Data app.
"""
from django.conf import settings
from django.conf.urls import url
from django.views.generic import TemplateView

from . import RDF_SUPPORTED_EXTENSIONS
from .views import SnorqlTemplateView, remote_sparql, LoDRedirectView, LoDDataView, LoDHTMLView, remote_sparql_test, \
    PropertyTemplateView, EDMHTMLMockView, HubIDRedirectView, UserGeneratedContentList, UserGeneratedContentDetail

RDF_SUPPORTED_FORMATS = "|".join(RDF_SUPPORTED_EXTENSIONS)


def get_lod_detail_view_class():
    cls = getattr(settings, "LOD_HTML_DETAIL_VIEW", "nave.lod.views.LoDHTMLView")
    module_name, class_name = cls.rsplit(".", 1)
    import importlib
    module = importlib.import_module(module_name)
    return getattr(module, class_name)

lod_html_detail_view = get_lod_detail_view_class()

urlpatterns = [
    url(r'^lod-detail/?$', EDMHTMLMockView.as_view()),
    url(r'^lod/statistics/$', TemplateView.as_view(template_name="lod_statistics.html")), #  mocked

    url(r'^(?P<namespace>(.*?))/ns/(?P<label>(.*)$)', PropertyTemplateView.as_view(), name="properties"),
    url(r'snorql/$', SnorqlTemplateView.as_view(), name="snorql_main"),
    url(r'^sparql/$', remote_sparql, name='proxy'),
    url(r'^id/(?P<reluri>(.*?))$', remote_resolve, name='remote_resolve'),
    url(r'^sparql_test/$', remote_sparql_test),
    url(r'^relfinder/$', TemplateView.as_view(template_name='relfinder.html'), name='relfinder'),
    url(r'^hub_version/$', TemplateView.as_view(template_name='version_number.html'), name='hum_version'),

    # hubId
    url(r'^resolve/(?P<doc_type>(.*?))/(?P<hubId>(.*?))/$', HubIDRedirectView.as_view()),
    url(r'^api/resolve/(?P<doc_type>(.*?))/(?P<hubId>(.*?))/$', HubIDRedirectView.as_view()),
    url(r'api/resolve/(?P<hubId>(.*?))/?$', HubIDRedirectView.as_view(), name='api_redirect_hub_id'),
    url(r'^{}/(?P<spec>(.*))/(?P<local_id>(.*))$'.format(settings.ORG_ID), HubIDRedirectView.as_view(), name='hub_id_redirect'),

    # redirects
    url(r'^resource/(?P<type_>(.*))/(?P<label>(.*))\.(?P<extension>({}))$'.format(
        RDF_SUPPORTED_FORMATS), LoDRedirectView.as_view()),
    url(r'^resource/(?P<type_>(.*))/(?P<label>(.*))$', LoDRedirectView.as_view(),
        name="typed_lod_resource_page"),
    url(r'^resource/(?P<type_>(.*))/(?P<label>(.*))$', LoDRedirectView.as_view()),
    url(r'^resource/(?P<label>(.*))$', LoDRedirectView.as_view()),
    url(r'^resource/(?P<label>(.*))\.(?P<extension>({}))$'.format(RDF_SUPPORTED_FORMATS),
        LoDRedirectView.as_view()),
    url(r'^page/(?P<label>(.*))\.(?P<extension>({}))$'.format(RDF_SUPPORTED_FORMATS),
        LoDRedirectView.as_view()),
    url(r'^page/(?P<type_>(.*))/(?P<label>(.*))\.(?P<extension>({}))$'.format(RDF_SUPPORTED_FORMATS),
        LoDRedirectView.as_view()),
    url(r'^data/(?P<type_>(.*))/(?P<label>([^\.]*))$', LoDRedirectView.as_view()),
    url(r'^data/(?P<label>([^\.]*))$', LoDRedirectView.as_view()),

    # edm page view  (only for direct view)
    url(r'page/aggregation/(?P<label>(.*))$',
        lod_html_detail_view.as_view(),
        name="edm_lod_page_detail"),

    # page views
    url(r'^page/(?P<type_>(.*))/(?P<label>(.*))$',
        lod_html_detail_view.as_view(),
        name="typed_lod_page_detail"),
    url(r'^page/(?P<label>(.*))$',
        lod_html_detail_view.as_view(),
        name="lod_page_detail"),


    # data views
    url(r'^data/(?P<type_>(.*))/(?P<label>(.*))\.(?P<extension>({}))$'.format(RDF_SUPPORTED_FORMATS),
        LoDDataView.as_view(),
        name="typed_lod_data_detail"),
    url(r'^data/(?P<label>(.*))\.(?P<extension>({}))$'.format(RDF_SUPPORTED_FORMATS),
        LoDDataView.as_view(),
        name="lod_data_detail"),
    # /schema
    #url(r'^schema\.(?P<extension>(.*))$', lod_html_detail_view.as_view(), name="rdf_schema"),
    #url(r'^schema)$', LoDHTMLView.as_view(), name="rdf_schema_data"),
    # /resource/class/id

    url(r'^api/enrich/ugc/$', UserGeneratedContentList.as_view()),
    url(r'^api/enrich/ugc/(?P<pk>[0-9]+)/$', UserGeneratedContentDetail.as_view()),
]

nave/urls.py
import os

from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic import TemplateView
from nave.common import views

from nave.search.views import LegacyAPIRedirectView

admin.autodiscover()
urlpatterns = [
    url(r'^', include('nave.void.urls')),
    url(r'^version/$', views.nave_version),
    url(r'^whoami/$', views.whoami),
    url(r'^', include('nave.webresource.urls')),
    url(r'^crossdomain.xml$', TemplateView.as_view(template_name='crossdomain.xml')),
    url(r'^robots.txt$', TemplateView.as_view(template_name='robots.txt')),
    url(r'^humans.xml$', TemplateView.as_view(template_name='humans.txt')),
    url(r'^watchman/', include('watchman.urls')),
    url(r'^rosetta/', include('rosetta.urls')),
]


if settings.USE_WAGTAIL_CMS:
    from wagtail.wagtailadmin import urls as wagtailadmin_urls
    from wagtail.wagtaildocs import urls as wagtaildocs_urls
    urlpatterns += i18n_patterns(
        url(r'^cms/', include(wagtailadmin_urls)),
        url(r'^documents/', include(wagtaildocs_urls)),
        prefix_default_language=False
    )


urlpatterns += i18n_patterns(
    url(r'^admin/', include(admin.site.urls)),  # NOQA
    url(r'^api-auth', include('rest_framework.urls', namespace='rest_framework')),
    url(r'narthex/', views.NarthexRedirectView.as_view()),
    url(r'^api/search/$', LegacyAPIRedirectView.as_view(), name='api_redirect'),
    url(r'^', include('nave.projects.{}.urls'.format(settings.SITE_NAME))),
    url(r'^', include('nave.search.urls')),
    url(r'^', include('nave.virtual_collection.urls')),
    url(r'^', include('nave.virtual_website.urls')),
    url(r'^', include('nave.lod.urls')),
    url(r'^', include('nave.search_widget.urls')),
    # template and data from nave.void app
    url(r'^statistics/', TemplateView.as_view(template_name="statistics.html")),
    url(r'^o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    prefix_default_language=False
)



if settings.USE_WAGTAIL_CMS:
    from wagtail.wagtailcore import urls as wagtail_urls
    urlpatterns += i18n_patterns(
        url(r'^', include(wagtail_urls)),
        prefix_default_language=False
    )

    if os.path.exists(os.path.join(settings.DJANGO_ROOT, "projects", settings.SITE_NAME, "wagtail_urls.py")):
        urlpatterns += [
            url(r'^', include('nave.projects.{}.wagtail_urls'.format(settings.SITE_NAME)))
        ]


staticurls = [('^%s$' % f, 'redirect_to', {'url': settings.STATIC_URL + f}) for f in
              ('crossdomain.xml', 'robots.txt', 'humans.txt')]


# This is only needed when using runserver.
if settings.DEBUG:
    import django
    urlpatterns = [
        url(r'^media/(?P<path>.*)$', django.views.static.serve,  # NOQA
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
    ] + staticfiles_urlpatterns() + urlpatterns  # NOQA

nave/webresource/urls.py
"""
Note:

    Make sure this url configuration is included in your main configuration
    as follows:

    url(r'^', include('webresource.urls')),
"""
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        r'api/webresource/$',
        views.WebResourceRedirectView.as_view(),
        name="webresource"
    ),
    url(
        r'api/webresource/deepzoom/(?P<urn>.*$)',
        views.DeepZoomRedirectView.as_view(),
        name="webresource_deepzoom"
    ),
    url(
        r'api/deepzoom/(?P<webresource>.*$)',
        views.DeepZoomRedirectView.as_view(),
        name="webresource_deepzoom_resolve"
    ),
    url(
        r'api/webresource/_docs/$',
        views.webresource_docs,
        name="webresource_docs"
    )
    # todo: include the references to statistics as well
    # for example _statistics _docs etc
]

nave/diw/models.py
from django.db import models
from django.utils.translation import ugettext, ugettext_lazy as _
from django.core.urlresolvers import reverse
from django_extensions.db.fields import AutoSlugField


class DiwInstance(models.Model):
    """
    Basic model for a Delving Instant Website Instance
    """
    name = models.CharField(
            max_length=55,
            help_text=_("Name of the Delving Instant Website Instance (should be descriptive of the end user)"),
            verbose_name=_("DIW Name")
    )

    endpoint = models.CharField(
        max_length=255,
        help_text=_("Base URL of the api"),
        verbose_name=_("Endpoint")
    )

    orig_id = models.CharField(
        max_length=55,
        help_text=_("Nave org-id of the Endpoint domain"),
        verbose_name=_("Nave organization id")
    )

    collection_spec = models.CharField(
        max_length=55,
        help_text=_("The spec of the dataset to be queried"),
        verbose_name=_("Spec")
    )

    data_provider = models.CharField(
        max_length=55,
        help_text=_("The name of the dataprovider"),
        verbose_name=_("Data provider")
    )

    show_config_help = models.BooleanField(
        default=False,
        help_text=_("Show configuration help in the preview. UN-CHECK/TURN OFF before creating a zip for download"),
        verbose_name=_("Show configuration help")
    )

    slug = AutoSlugField(populate_from='name')

    class Meta(object):
        verbose_name = _("DIW Instance")
        verbose_name_plural = _("DIW Instances")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('diw_instance', kwargs={'slug': self.slug})


class DiwFacet(models.Model):
    """
    Facets to be retrieved and displayed
    """
    diw = models.ForeignKey(
        DiwInstance,
        related_name="facets"
    )

    name = models.CharField(
        max_length=55,
        blank=False,
        help_text=_("The desired field to retrieve ie: dc_creator_facet, dc_subject_facet"),
        verbose_name=_("Facet field")
    )

    label = models.CharField(
        max_length=55,
        blank=False,
        help_text=_("The label to appear above the list of retrieved facets"),
        verbose_name=_("Facet header")
    )

    position = models.PositiveSmallIntegerField(
        "Position",
        default=0
    )

    class Meta:
        verbose_name = _("Facet")
        verbose_name_plural = _("Facets")
        ordering = ['position']


class DiwResultField(models.Model):
    """
    Fields to be displayed with the intial returned results
    """
    diw = models.ForeignKey(
        DiwInstance,
        related_name="resultfields"
    )

    name = models.CharField(
        max_length=55,
        blank=False,
        help_text=_("The desired field to retrieve ie: dc_title, dc_creator, dcterms_provenance"),
        verbose_name=_("Field name")
    )

    label = models.CharField(
        max_length=55,
        blank=True,
        help_text=_("The label to be displayed before the field value - if left blank no label will be displayed (not recommended)"),
        verbose_name=_("Field label")
    )

    position = models.PositiveSmallIntegerField(
        "Position",
        default=0
    )

    class Meta:
        verbose_name = _("Result field")
        verbose_name_plural = _("Result fields")
        ordering = ['position']


class DiwDetailField(models.Model):
    """
    Fields to be displayed on the detail view
    """
    diw = models.ForeignKey(
        DiwInstance,
        related_name="detailfields"
    )

    name = models.CharField(
        max_length=55,
        blank=False,
        help_text=_("The desired field to retrieve ie: dc_title, dc_creator, dcterms_provenance"),
        verbose_name=_("Field name")
    )

    label = models.CharField(
        max_length=55,
        blank=True,
        help_text=_("The label to be displayed before the field value - if left blank no label will be displayed (not recommended)"),
        verbose_name=_("Field label")
    )

    position = models.PositiveSmallIntegerField(
        "position",
        default=0
    )

    class Meta:
        verbose_name = _("Item field")
        verbose_name_plural = _("Item fields")
        ordering = ['position']

nave/virtual_website/models.py
# -*- coding: utf-8 -*-
"""Models for Django Virtual Website App."""
from django.urls import reverse
from django.db import models
from django.http import QueryDict
from django_extensions.db.fields import AutoSlugField
from django_extensions.db.models import TimeStampedModel
from django.utils.translation import ugettext_lazy as _

from nave.void.models import GroupOwned


class VirtualWebsite(TimeStampedModel, GroupOwned):
    """
    The models holds the information for the Virtual collections
    """
    title = models.CharField(
        _("title"),
        max_length=512
    )
    slug = AutoSlugField(populate_from='title')
    body = models.TextField(
        _("body"),
        blank=True,
        null=True
    )
    query = models.TextField(
        _("query"),
        blank=True,
        null=True,
        help_text=_("The full query as used on the search page or search API.")
    )
    oai_pmh = models.BooleanField(
        _("published"),
        default=True,
        help_text=_("Is this collection publicly available.")
    )
    published = models.BooleanField(
        _("published"),
        default=True,
        help_text=_("Is this collection publicly available.")
    )
    owner = models.CharField(
        _("owner key"),
        max_length=512,
        blank=True,
        null=True,
        help_text=_("profile ID, user key, etc")
    )
    creator = models.CharField(
        _("creator"),
        max_length=512,
        blank=True,
        null=True,
        help_text=_("name or institution")
    )
    # fields for diw virtual collection
    diw_header = models.TextField(
        _("diw header"),
        blank=True,
        null=True
    )
    diw_footer = models.TextField(
        _("diw footer"),
        blank=True,
        null=True
    )
    diw_css = models.TextField(
        _("diw css"),
        blank=True,
        null=True
    )
    diw_config = models.TextField(
        _("diw configuration"),
        blank=True,
        null=True
    )
    # This url can be used for navigation
    external_url = models.CharField(
        _("external URL"),
        max_length=512,
        blank=True,
        null=True,
        help_text=_("extern URL voor de virtuele website.")
    )

    class Meta(object):
        verbose_name = _("Virtual Website")
        verbose_name_plural = _("Virtual Websites")

    def __str__(self):
        return self.title

    # work with external URL as well
    # or use relative linking
    def get_absolute_url(self):
        return reverse('virtual_website_detail', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        allowed_filters = ["qf=", 'hfq=', "q=", "hqf[]=", "qf[]="]
        if any(key in self.query for key in allowed_filters):
            # create the proper format string
            filter_list = []
            query_dict = QueryDict(query_string=self.query.split("?", maxsplit=1)[-1])
            for k, v in query_dict.items():
                if any([key.startswith(k) for key in allowed_filters]) and v:
                    applied_filter = query_dict.getlist(k)
                    filter_list.extend(applied_filter)
            self.query = ";;;".join(["\"{}\"".format(k) for k in filter_list])
        super(VirtualWebsite, self).save(*args, **kwargs)


class VirtualWebsitePage(TimeStampedModel, GroupOwned):
    """
    This model holds a custom page for a virtual collection.
    """
    title = models.CharField(
        _("title"),
        max_length=512
    )
    slug = AutoSlugField(
            populate_from=['diw__title', 'title']
    )
    page_body = models.TextField(
        _("page body"),
        blank=True,
        null=True
    )
    diw = models.ForeignKey(
        VirtualWebsite,
        on_delete=models.CASCADE,
        related_name="pages"
    )
    show_search = models.BooleanField(
        _("show search"),
        default=True,
        help_text=_("show search bar on virtual collection page")
    )

    class Meta:
        verbose_name = _("Page")
        verbose_name_plural = _("Pages")
        ordering = ['slug']

nave/lod/templates/rdf/include/enrichment_block_admin.html
{% load enrichment_tags %}
<article class="ugc-block ugc-block--{{ item.content_type }}">
    {% if item.content_type == 'youtube' %}
        <a class="ugc-block__thumb ugc-block__thumb--youtube"
           href="{{ item.link }}"
           target="_blank">
            <img src="{% youtube_thumbnail item.link %}"
                 alt="{{ item.name }}">
        </a>
    {% endif %}
    <h2 class="ugc-block__title">
        {# Using name field as title for now #}
        {{ item.name }}
    </h2>
    <p class="ugc-block__description">
        {{ item.short_description }}
    </p>
    {% if item.link %}
        <a href="{{ item.link }}"
           class="ugc-block__more"
           target="_blank">
        <span>Lees meer</span>
        </a>
    {% endif %}

    <form name="ugc-block-info-form" id="ugc-info-block-form-{{ forloop.counter }}">
        <input type="hidden" name="id" value="{{ item.id }}"/>
        <input type="hidden" name="source_uri" value="{{ item.source_uri }}"/>
        <input type="hidden" name="content_type" value="{{ item.content_type }}"/>
        <input type="hidden" name="name" value="{{ item.name }}"/>
        <input type="hidden" name="short_description" value="{{ item.short_description }}"/>
        <input type="hidden" name="link" value="{{ item.link }}"/>
        <input type="hidden" name="published" value="{{ item.published }}"/>

        <div class="ugc-block__actions">
            {# TODO: add edit and delete functionality for ugc item #}
            <button id="ugc-block-edit-button-{{ forloop.counter }}" class="btn btn-info ugc-block-edit-button"><i class="fa fa-edit"></i></button>
            {# <button id="ugc-block-unpublish-button-{{ forloop.counter }}" class="btn btn-danger ugc-block-unpublish-button"><i class="fa fa-trash-o"></i></button>#}
            {% if not item.published %}
                <span class="not-published">NOT PUBLISHED</span>
            {% endif %}
        </div>
    </form>

</article>

nave/lod/templates/rdf/include/enrichment_block_display.html
{% load enrichment_tags %}
<article class="ugc-block ugc-block--{{ item.content_type }}">
    {% if item.content_type == 'youtube' %}
        <a class="ugc-block__thumb ugc-block__thumb--youtube"
           href="{{ item.link }}"
           target="_blank">
            <img src="{% youtube_thumbnail item.link %}"
                 alt="{{ item.name }}">
        </a>
    {% endif %}
    {# add unplished ones as well but only for logged in user #}
    <h2 class="ugc-block__title">
        {# Using name field as title for now #}
        {{ item.name }}
    </h2>
    {# type: {{ item.content_type }}<br/> #}
    <p class="ugc-block__description">
        {{ item.short_description }}
    </p>
    {% if item.link %}
        <a href="{{ item.link }}"
           class="ugc-block__more"
           target="_blank">
            <span>
            Lees meer
            </span>
        </a>
    {% endif %}
</article>

nave/lod/templates/rdf/include/enrichment_link_form.html
{% load i18n static %}
<div class="bs-callout bs-callout-warning hidden">
    <h4>Oh snap!</h4>
    <p>This form seems to be invalid :(</p>
</div>
<div class="bs-callout bs-callout-info hidden">
    <h4>Yay!</h4>
    <p>Everything seems to be ok :)</p>
</div>
<form data-parsley-validate="" action="" method="post" id="enrichment_link_form" role="form" class="form">
    {% csrf_token %}
    <input type="hidden" name="source_uri" id="id_source_uri" value="{{ source_uri }}"/>
    <div class="form-group">
        <label for="id-content_type" class="control-label">{% trans 'Type' %}</label>
        <input type="text" required="" class="form-control" id="id_content_type" placeholder="{% trans 'Type' %}">
    </div>
    <div class="form-group">
        <label for="id_name" class="control-label">{% trans 'Name' %}</label>
        <input type="text" required="" class="form-control" id="id_name" placeholder="{% trans 'Name' %}">
    </div>
    <div class="form-group">
        <label for="id_short_description" class="control-label">{% trans 'Short description' %}</label>
        <input type="text" required="" class="form-control" id="id_short_description" placeholder="{% trans 'Short description' %}">
    </div>
    <div class="form-group">
        <label for="id_link" class="control-label">{% trans 'URL/Link' %}</label>
        <input type="url" required="" class="form-control" id="id_link" placeholder="{% trans 'Link' %}">
    </div>
    <div class="form-group">
        <label for="id_published" class="control-label">{% trans 'Published' %}</label>
        <input type="checkbox" required="" name="published" id="id_published" value="true" checked="true"/>
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-primary">{% trans 'Save' %}</button>
    </div>
</form>